// pcre2-bless runs the PCRE2 conformance harness and rewrites the
// known-failures file to match today's reality. Run after engine progress
// to lock in gains; review the diff before committing.
//
//	go run ./cmd/pcre2-bless              # write testdata/pcre2_known_failures.txt
//	go run ./cmd/pcre2-bless -dry-run     # print what would change
//	go run ./cmd/pcre2-bless -verbose     # also print each outcome
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/jettero/pcrec"
)

func main() {
	corpus := flag.String("corpus", "contrib/pcre2/testdata/testoutput1", "testoutputN file to read")
	inputName := flag.String("input-name", "testinput1", "name used as ID prefix")
	out := flag.String("out", "testdata/pcre2_known_failures.txt", "known-failures file to write")
	dry := flag.Bool("dry-run", false, "don't write; just print the diff")
	verbose := flag.Bool("verbose", false, "print each outcome")
	flag.Parse()

	pats, err := pcrec.LoadConformancePatterns(*corpus)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load corpus:", err)
		os.Exit(1)
	}
	existing, err := pcrec.LoadKnownFailures(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load existing:", err)
		os.Exit(1)
	}

	stats := pcrec.NewStats()
	prog := func(i, n int) {
		if i%50 == 0 || i == n-1 {
			fmt.Fprintf(os.Stderr, "\rpattern %d/%d ", i+1, n)
		}
	}
	outcomes := pcrec.EvaluateAll(*inputName, pats, prog)
	fmt.Fprintln(os.Stderr) // newline after progress line

	type fail struct {
		ID     string
		Bucket pcrec.Bucket
		Reason string
	}
	var fails []fail
	for _, oc := range outcomes {
		stats.Add(oc, existing)
		if *verbose {
			fmt.Printf("%-8s %s :: %s\n", oc.Bucket, oc.ID, oc.Reason)
		}
		if oc.Bucket.IsFail() {
			fails = append(fails, fail{ID: oc.ID, Bucket: oc.Bucket, Reason: oc.Reason})
		}
	}
	sort.Slice(fails, func(i, j int) bool { return idLess(fails[i].ID, fails[j].ID) })

	// Build new file contents.
	var nb strings.Builder
	fmt.Fprintln(&nb, "# PCRE2 conformance known-failures — regenerated by `go run ./cmd/pcre2-bless`.")
	fmt.Fprintln(&nb, "# Format: <ID>  # <bucket>: <reason>")
	fmt.Fprintln(&nb, "# Each line is one (pattern, subject) outcome currently failing.")
	fmt.Fprintln(&nb, "# Removing an ID and re-running the test will require the engine to PASS it.")
	fmt.Fprintln(&nb, "")
	for _, f := range fails {
		fmt.Fprintf(&nb, "%s  # %s: %s\n", f.ID, f.Bucket, oneLine(f.Reason))
	}

	// Diff against existing IDs only (comments/reasons we expect to change freely).
	newIDs := map[string]bool{}
	for _, f := range fails {
		newIDs[f.ID] = true
	}
	var added, removed []string
	for id := range newIDs {
		if !existing[id] {
			added = append(added, id)
		}
	}
	for id := range existing {
		if !newIDs[id] {
			removed = append(removed, id)
		}
	}
	sort.Strings(added)
	sort.Strings(removed)

	fmt.Println(stats.Summary())
	fmt.Printf("known-failures diff vs %s:\n", *out)
	fmt.Printf("  +added:   %d\n", len(added))
	fmt.Printf("  -removed: %d\n", len(removed))
	if *verbose {
		for _, id := range added {
			fmt.Printf("  +%s\n", id)
		}
		for _, id := range removed {
			fmt.Printf("  -%s\n", id)
		}
	}

	if *dry {
		fmt.Println("(dry-run; not writing)")
		return
	}
	if err := os.MkdirAll(dirOf(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(nb.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d entries)\n", *out, len(fails))
}

func dirOf(path string) string {
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		return path[:i]
	}
	return "."
}

// idLess sorts IDs as (file, line-number) so testinput1:9 comes before
// testinput1:10, not the lexicographic 10<9.
func idLess(a, b string) bool {
	af, al := splitID(a)
	bf, bl := splitID(b)
	if af != bf {
		return af < bf
	}
	return al < bl
}

func splitID(id string) (string, int) {
	i := strings.LastIndexByte(id, ':')
	if i < 0 {
		return id, 0
	}
	n := 0
	for _, c := range id[i+1:] {
		if c < '0' || c > '9' {
			return id, 0
		}
		n = n*10 + int(c-'0')
	}
	return id[:i], n
}

// oneLine collapses to a single line for the inline comment.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > 160 {
		s = s[:160] + "…"
	}
	return s
}
