fail_fast: true

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
    args: [ "-s" ]
  - id: go-imports
  - id: go-mod-tidy
  - id: validate-toml
  - id: go-unit-tests
    exclude: '(cruft|cmd)'
  # id: go-lint
  # id: go-critic
  # id: go-vet
  # id: go-cyclo
  # args: [-over=15]
  # id: no-go-testing
  # id: golangci-lint
  # id: go-build

- repo: local
  hooks:
  - id: wtf
    name: WTF
    entry: '\b(?i:wtf)\b'
    types: [ go ]
    language: pygrep
