fail_fast: true

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
    args: [ "-s" ]

- repo: local
  hooks:
  - id: wtf
    name: WTF
    entry: '\b(?i:wtf)\b'
    types: [ go ]
    language: pygrep
